/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd.edu.daffodilvarsity.studentdatabase;


/**
 *
 * @author Mushfiqus Salehin
 */
public class AddPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPanel
     */
    public AddPanel() {
        initComponents();
        panelVisiblity(true, false, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        findButton = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        viewResultButton = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        admitStudentButton = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        dropStudentButton = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        findStudentField = new javax.swing.JTextField();
        addStudentPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        nameLabel4 = new javax.swing.JLabel();
        nameField4 = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        idLabel4 = new javax.swing.JLabel();
        idField4 = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        fathersNameField4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        genderLabel4 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList10 = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList11 = new javax.swing.JList<>();
        motherLabel4 = new javax.swing.JLabel();
        femaleCheck4 = new javax.swing.JRadioButton();
        maleCheck4 = new javax.swing.JRadioButton();
        createProfileButtonPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        addButtonPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        showSelectedCourses4 = new javax.swing.JLabel();
        mothersNameField4 = new javax.swing.JTextField();
        fatherLabel4 = new javax.swing.JLabel();
        mainFromAdmit = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        addButtonPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        dropStudentPanel = new javax.swing.JPanel();
        dropSearchStudentPanel = new javax.swing.JPanel();
        jSeparator12 = new javax.swing.JSeparator();
        findStudentDropField = new javax.swing.JTextField();
        mainFromDrop1 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        dropStudentSearchButton1 = new javax.swing.JPanel();
        dropStudentSearchButtonLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dropFoundStudentPanel = new javax.swing.JPanel();
        mainFromDrop2 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        dropStudentSearchButton2 = new javax.swing.JPanel();
        dropStudentSearchButtonLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        resultPanel = new javax.swing.JPanel();
        resultSearchPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        resultSearchButton1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        mainFromResult1 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        resultSearchField1 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        resultViewPanel = new javax.swing.JPanel();
        mainFromResult4 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 47, 65));
        setForeground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomePanel.setBackground(new java.awt.Color(36, 47, 65));
        welcomePanel.setForeground(new java.awt.Color(204, 204, 204));
        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeText.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 255, 255));
        welcomeText.setText("Welcome to Student Database");
        welcomePanel.add(welcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 360, 50));

        findButton.setBackground(new java.awt.Color(50, 132, 255));
        findButton.setForeground(new java.awt.Color(255, 255, 255));
        findButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("FIND");
        findButton.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        welcomePanel.add(findButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 100, 40));
        welcomePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 330, 30));

        viewResultButton.setBackground(new java.awt.Color(50, 132, 255));
        viewResultButton.setForeground(new java.awt.Color(255, 255, 255));
        viewResultButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewResultButtonMouseClicked(evt);
            }
        });
        viewResultButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("VIEW RESULT");
        viewResultButton.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 120, 50));
        viewResultButton.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 20));

        welcomePanel.add(viewResultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 180, 50));

        admitStudentButton.setBackground(new java.awt.Color(50, 132, 255));
        admitStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        admitStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admitStudentButtonMouseClicked(evt);
            }
        });
        admitStudentButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("ADMIT STUDENT");
        admitStudentButton.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        admitStudentButton.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 20));

        welcomePanel.add(admitStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 180, 50));

        dropStudentButton.setBackground(new java.awt.Color(50, 132, 255));
        dropStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropStudentButtonMouseClicked(evt);
            }
        });
        dropStudentButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("DROP STUDENT");
        dropStudentButton.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 50));
        dropStudentButton.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 20));

        welcomePanel.add(dropStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 180, 50));

        findStudentField.setBackground(new java.awt.Color(36, 47, 65));
        findStudentField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        findStudentField.setForeground(new java.awt.Color(204, 204, 204));
        findStudentField.setText("Enter ID to find");
        findStudentField.setBorder(null);
        findStudentField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findStudentFieldMouseClicked(evt);
            }
        });
        findStudentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findStudentFieldActionPerformed(evt);
            }
        });
        welcomePanel.add(findStudentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 330, 40));

        add(welcomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        addStudentPanel.setBackground(new java.awt.Color(36, 47, 65));
        addStudentPanel.setForeground(new java.awt.Color(204, 204, 204));
        addStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("STUDENT DETAILS");
        addStudentPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jSeparator21.setOrientation(javax.swing.SwingConstants.VERTICAL);
        addStudentPanel.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 20, 390));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SELECT COURSES");
        addStudentPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        nameLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        nameLabel4.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel4.setText("FULL NAME");
        addStudentPanel.add(nameLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        nameField4.setBackground(new java.awt.Color(36, 47, 65));
        nameField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nameField4.setForeground(new java.awt.Color(204, 204, 204));
        nameField4.setText("Enter name");
        nameField4.setBorder(null);
        nameField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameField4MouseClicked(evt);
            }
        });
        nameField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameField4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(nameField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 40));
        addStudentPanel.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, -1));

        idLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        idLabel4.setForeground(new java.awt.Color(255, 255, 255));
        idLabel4.setText("ID");
        addStudentPanel.add(idLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        idField4.setBackground(new java.awt.Color(36, 47, 65));
        idField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        idField4.setForeground(new java.awt.Color(204, 204, 204));
        idField4.setText("Enter student ID");
        idField4.setBorder(null);
        idField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idField4MouseClicked(evt);
            }
        });
        idField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idField4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(idField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, 40));
        addStudentPanel.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, -1));

        fathersNameField4.setBackground(new java.awt.Color(36, 47, 65));
        fathersNameField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        fathersNameField4.setForeground(new java.awt.Color(204, 204, 204));
        fathersNameField4.setText("Enter name");
        fathersNameField4.setBorder(null);
        fathersNameField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fathersNameField4MouseClicked(evt);
            }
        });
        fathersNameField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathersNameField4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(fathersNameField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, 40));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("SELECTED COURSES:");
        addStudentPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));
        addStudentPanel.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 200, -1));

        genderLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        genderLabel4.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel4.setText("GENDER");
        addStudentPanel.add(genderLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));
        addStudentPanel.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 200, -1));

        jList10.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CSE121", "CSE 122", "CSE 123", "CSE 221", "CSE 222", "CSE 223" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(jList10);

        addStudentPanel.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 110, 230));

        jList11.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CSE121", "CSE 122", "CSE 123", "CSE 221", "CSE 222", "CSE 223" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(jList11);

        addStudentPanel.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 120, 230));

        motherLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        motherLabel4.setForeground(new java.awt.Color(255, 255, 255));
        motherLabel4.setText("MOTHER'S NAME");
        addStudentPanel.add(motherLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        femaleCheck4.setBackground(new java.awt.Color(36, 47, 65));
        femaleCheck4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        femaleCheck4.setForeground(new java.awt.Color(255, 255, 255));
        femaleCheck4.setText("FEMALE");
        femaleCheck4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleCheck4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(femaleCheck4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        maleCheck4.setBackground(new java.awt.Color(36, 47, 65));
        maleCheck4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        maleCheck4.setForeground(new java.awt.Color(255, 255, 255));
        maleCheck4.setText("MALE");
        maleCheck4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleCheck4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(maleCheck4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        createProfileButtonPanel4.setBackground(new java.awt.Color(50, 132, 255));
        createProfileButtonPanel4.setForeground(new java.awt.Color(255, 255, 255));
        createProfileButtonPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("CREATE PROFILE");
        createProfileButtonPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 30));

        addStudentPanel.add(createProfileButtonPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 180, 50));

        addButtonPanel4.setBackground(new java.awt.Color(255, 52, 36));
        addButtonPanel4.setForeground(new java.awt.Color(255, 255, 255));
        addButtonPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("<<REMOVE");
        addButtonPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 80, -1));

        addStudentPanel.add(addButtonPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 90, 40));

        showSelectedCourses4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        showSelectedCourses4.setForeground(new java.awt.Color(255, 0, 102));
        showSelectedCourses4.setText("0");
        addStudentPanel.add(showSelectedCourses4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 70, 20));

        mothersNameField4.setBackground(new java.awt.Color(36, 47, 65));
        mothersNameField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        mothersNameField4.setForeground(new java.awt.Color(204, 204, 204));
        mothersNameField4.setText("Enter name");
        mothersNameField4.setBorder(null);
        mothersNameField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mothersNameField4MouseClicked(evt);
            }
        });
        mothersNameField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothersNameField4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(mothersNameField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 200, 40));

        fatherLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        fatherLabel4.setForeground(new java.awt.Color(255, 255, 255));
        fatherLabel4.setText("FATHER'S NAME");
        addStudentPanel.add(fatherLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        mainFromAdmit.setBackground(new java.awt.Color(36, 47, 65));
        mainFromAdmit.setForeground(new java.awt.Color(255, 255, 255));
        mainFromAdmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromAdmitMouseClicked(evt);
            }
        });
        mainFromAdmit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("BACK TO MAIN MENU");
        mainFromAdmit.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromAdmit.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 20));

        addStudentPanel.add(mainFromAdmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        addButtonPanel5.setBackground(new java.awt.Color(38, 177, 76));
        addButtonPanel5.setForeground(new java.awt.Color(255, 255, 255));
        addButtonPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("ADD>>");
        addButtonPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 50, -1));

        addStudentPanel.add(addButtonPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 90, 40));

        add(addStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dropStudentPanel.setBackground(new java.awt.Color(36, 47, 65));
        dropStudentPanel.setForeground(new java.awt.Color(204, 204, 204));
        dropStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropSearchStudentPanel.setBackground(new java.awt.Color(36, 47, 65));
        dropSearchStudentPanel.setForeground(new java.awt.Color(204, 204, 204));
        dropSearchStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        dropSearchStudentPanel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 330, 30));

        findStudentDropField.setBackground(new java.awt.Color(36, 47, 65));
        findStudentDropField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        findStudentDropField.setForeground(new java.awt.Color(204, 204, 204));
        findStudentDropField.setText("Enter Student ID");
        findStudentDropField.setBorder(null);
        findStudentDropField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findStudentDropFieldMouseClicked(evt);
            }
        });
        findStudentDropField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findStudentDropFieldActionPerformed(evt);
            }
        });
        dropSearchStudentPanel.add(findStudentDropField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 330, 40));

        mainFromDrop1.setBackground(new java.awt.Color(36, 47, 65));
        mainFromDrop1.setForeground(new java.awt.Color(255, 255, 255));
        mainFromDrop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromDrop1MouseClicked(evt);
            }
        });
        mainFromDrop1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("BACK TO MAIN MENU");
        mainFromDrop1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromDrop1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        dropSearchStudentPanel.add(mainFromDrop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        dropStudentSearchButton1.setBackground(new java.awt.Color(50, 132, 255));
        dropStudentSearchButton1.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentSearchButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropStudentSearchButtonLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        dropStudentSearchButtonLabel1.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentSearchButtonLabel1.setText("DROP");
        dropStudentSearchButton1.add(dropStudentSearchButtonLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 40));

        dropSearchStudentPanel.add(dropStudentSearchButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 100, 40));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Drop Student");
        dropSearchStudentPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 190, 40));

        dropStudentPanel.add(dropSearchStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dropFoundStudentPanel.setBackground(new java.awt.Color(36, 47, 65));
        dropFoundStudentPanel.setForeground(new java.awt.Color(204, 204, 204));
        dropFoundStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainFromDrop2.setBackground(new java.awt.Color(36, 47, 65));
        mainFromDrop2.setForeground(new java.awt.Color(255, 255, 255));
        mainFromDrop2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromDrop2MouseClicked(evt);
            }
        });
        mainFromDrop2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("BACK TO MAIN MENU");
        mainFromDrop2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromDrop2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        dropFoundStudentPanel.add(mainFromDrop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        dropStudentSearchButton2.setBackground(new java.awt.Color(50, 132, 255));
        dropStudentSearchButton2.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentSearchButton2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropStudentSearchButtonLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        dropStudentSearchButtonLabel2.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentSearchButtonLabel2.setText("PROCEED");
        dropStudentSearchButton2.add(dropStudentSearchButtonLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 40));

        dropFoundStudentPanel.add(dropStudentSearchButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 120, 40));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("DROP STUDENT");
        dropFoundStudentPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 190, 40));

        dropStudentPanel.add(dropFoundStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(dropStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        resultPanel.setBackground(new java.awt.Color(36, 47, 65));
        resultPanel.setForeground(new java.awt.Color(204, 204, 204));
        resultPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultSearchPanel.setBackground(new java.awt.Color(36, 47, 65));
        resultSearchPanel.setForeground(new java.awt.Color(204, 204, 204));
        resultSearchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Result");
        resultSearchPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 190, 40));

        resultSearchButton1.setBackground(new java.awt.Color(50, 132, 255));
        resultSearchButton1.setForeground(new java.awt.Color(255, 255, 255));
        resultSearchButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("RESULT");
        resultSearchButton1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 40));

        resultSearchPanel.add(resultSearchButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 100, 40));

        mainFromResult1.setBackground(new java.awt.Color(36, 47, 65));
        mainFromResult1.setForeground(new java.awt.Color(255, 255, 255));
        mainFromResult1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromResult1MouseClicked(evt);
            }
        });
        mainFromResult1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("BACK TO MAIN MENU");
        mainFromResult1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromResult1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        resultSearchPanel.add(mainFromResult1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        resultSearchField1.setBackground(new java.awt.Color(36, 47, 65));
        resultSearchField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        resultSearchField1.setForeground(new java.awt.Color(204, 204, 204));
        resultSearchField1.setText("Enter Student ID");
        resultSearchField1.setBorder(null);
        resultSearchField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultSearchField1MouseClicked(evt);
            }
        });
        resultSearchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultSearchField1ActionPerformed(evt);
            }
        });
        resultSearchPanel.add(resultSearchField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 330, 40));
        resultSearchPanel.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 330, 30));

        resultPanel.add(resultSearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        resultViewPanel.setBackground(new java.awt.Color(36, 47, 65));
        resultViewPanel.setForeground(new java.awt.Color(204, 204, 204));
        resultViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainFromResult4.setBackground(new java.awt.Color(36, 47, 65));
        mainFromResult4.setForeground(new java.awt.Color(255, 255, 255));
        mainFromResult4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromResult4MouseClicked(evt);
            }
        });
        mainFromResult4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("BACK TO MAIN MENU");
        mainFromResult4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromResult4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        resultViewPanel.add(mainFromResult4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Result");
        resultViewPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 190, 40));

        resultPanel.add(resultViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(resultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField4MouseClicked

    private void nameField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField4ActionPerformed

    private void idField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idField4MouseClicked

    private void idField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idField4ActionPerformed

    private void fathersNameField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fathersNameField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fathersNameField4MouseClicked

    private void fathersNameField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathersNameField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathersNameField4ActionPerformed

    private void femaleCheck4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleCheck4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleCheck4ActionPerformed

    private void maleCheck4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleCheck4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleCheck4ActionPerformed

    private void mothersNameField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mothersNameField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mothersNameField4MouseClicked

    private void mothersNameField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothersNameField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothersNameField4ActionPerformed

    private void viewResultButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResultButtonMouseClicked
        //Need to implement dynamic views after setting up search fucntion
        displayResultPanel(true, false);
    }//GEN-LAST:event_viewResultButtonMouseClicked

    private void admitStudentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admitStudentButtonMouseClicked
        panelVisiblity(false, true, false, false);
    }//GEN-LAST:event_admitStudentButtonMouseClicked

    private void mainFromAdmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromAdmitMouseClicked
        panelVisiblity(true, false, false, false); //DONE
    }//GEN-LAST:event_mainFromAdmitMouseClicked

    private void dropStudentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropStudentButtonMouseClicked
        //Need to implement dynamic views after setting up search fucntion
        displayDropStudentPanel(true, false);
    }//GEN-LAST:event_dropStudentButtonMouseClicked

    private void findStudentFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findStudentFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_findStudentFieldMouseClicked

    private void findStudentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findStudentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findStudentFieldActionPerformed

    private void findStudentDropFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findStudentDropFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_findStudentDropFieldMouseClicked

    private void findStudentDropFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findStudentDropFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findStudentDropFieldActionPerformed

    private void mainFromDrop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromDrop1MouseClicked
        panelVisiblity(true, false, false, false); //DONE
    }//GEN-LAST:event_mainFromDrop1MouseClicked

    private void mainFromDrop2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromDrop2MouseClicked
        panelVisiblity(true, false, false, false); //DONE
    }//GEN-LAST:event_mainFromDrop2MouseClicked

    private void mainFromResult1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromResult1MouseClicked
       panelVisiblity(true, false, false, false); //DONE
    }//GEN-LAST:event_mainFromResult1MouseClicked

    private void resultSearchField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultSearchField1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resultSearchField1MouseClicked

    private void resultSearchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultSearchField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultSearchField1ActionPerformed

    private void mainFromResult4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromResult4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mainFromResult4MouseClicked

    //These methods are for displaying the Drop Student Panel  
    private void displayDropStudentPanel(boolean search, boolean found) {
        panelVisiblity(false,false, true, false);
        this.dropSearchStudentPanel.setVisible(search);
        this.dropFoundStudentPanel.setVisible(found);
    }
    
    //These methods are for displaying the Result Panel  
    private void displayResultPanel(boolean search, boolean view) {
        panelVisiblity(false,false, false, true);
        this.resultSearchPanel.setVisible(search);
        this.resultViewPanel.setVisible(view);
    }
    
    private void panelVisiblity(boolean welcomePanel, boolean addStudentPanel, boolean dropStudentPanel, boolean viewResultPanel){
        this.welcomePanel.setVisible(welcomePanel);
        this.addStudentPanel.setVisible(addStudentPanel);
        this.dropStudentPanel.setVisible(dropStudentPanel);
        this.resultPanel.setVisible(viewResultPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addButtonPanel4;
    private javax.swing.JPanel addButtonPanel5;
    private javax.swing.JPanel addStudentPanel;
    private javax.swing.JPanel admitStudentButton;
    private javax.swing.JPanel createProfileButtonPanel4;
    private javax.swing.JPanel dropFoundStudentPanel;
    private javax.swing.JPanel dropSearchStudentPanel;
    private javax.swing.JPanel dropStudentButton;
    private javax.swing.JPanel dropStudentPanel;
    private javax.swing.JPanel dropStudentSearchButton1;
    private javax.swing.JPanel dropStudentSearchButton2;
    private javax.swing.JLabel dropStudentSearchButtonLabel1;
    private javax.swing.JLabel dropStudentSearchButtonLabel2;
    private javax.swing.JLabel fatherLabel4;
    private javax.swing.JTextField fathersNameField4;
    private javax.swing.JRadioButton femaleCheck4;
    private javax.swing.JPanel findButton;
    private javax.swing.JTextField findStudentDropField;
    private javax.swing.JTextField findStudentField;
    private javax.swing.JLabel genderLabel4;
    private javax.swing.JTextField idField4;
    private javax.swing.JLabel idLabel4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JList<String> jList10;
    private javax.swing.JList<String> jList11;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel mainFromAdmit;
    private javax.swing.JPanel mainFromDrop1;
    private javax.swing.JPanel mainFromDrop2;
    private javax.swing.JPanel mainFromResult1;
    private javax.swing.JPanel mainFromResult4;
    private javax.swing.JRadioButton maleCheck4;
    private javax.swing.JLabel motherLabel4;
    private javax.swing.JTextField mothersNameField4;
    private javax.swing.JTextField nameField4;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JPanel resultSearchButton1;
    private javax.swing.JTextField resultSearchField1;
    private javax.swing.JPanel resultSearchPanel;
    private javax.swing.JPanel resultViewPanel;
    private javax.swing.JLabel showSelectedCourses4;
    private javax.swing.JPanel viewResultButton;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
