/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd.edu.daffodilvarsity.studentdatabase;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.*;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mushfiqus Salehin
 */
public class AddPanel extends javax.swing.JPanel {
    
    //Custom variables
    private ArrayList<Student> students = new ArrayList();
    private Student student = new Student();
    private ArrayList<Course> courses = new ArrayList<>(6);
    private int mainCourseCount = 0;
    
    /**
     * Creates new form AddPanel
     */
    public AddPanel() {
        initComponents();
        panelVisiblity(true, false, false, false);
        if (checkSaveFile()){
            loadStudentData();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        findButton = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        viewResultButton = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        admitStudentButton = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        dropStudentButton = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        findStudentField = new javax.swing.JTextField();
        admitStudentButton1 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        addStudentPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        nameLabel4 = new javax.swing.JLabel();
        addStudentFullName = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        idLabel4 = new javax.swing.JLabel();
        addStudentID = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        addFathersNameField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        genderLabel4 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        motherLabel4 = new javax.swing.JLabel();
        addFemaleCheck = new javax.swing.JRadioButton();
        addMaleCheck = new javax.swing.JRadioButton();
        createProfileButtonPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        showSelectedCoursesCount = new javax.swing.JLabel();
        addMothersNameField = new javax.swing.JTextField();
        fatherLabel4 = new javax.swing.JLabel();
        mainFromAdmit = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        cse101CheckBox = new javax.swing.JCheckBox();
        cse201CheckBox = new javax.swing.JCheckBox();
        cse301CheckBox = new javax.swing.JCheckBox();
        cse102CheckBox = new javax.swing.JCheckBox();
        cse202CheckBox = new javax.swing.JCheckBox();
        cse302CheckBox = new javax.swing.JCheckBox();
        cse103CheckBox = new javax.swing.JCheckBox();
        cse203CheckBox = new javax.swing.JCheckBox();
        cse303CheckBox = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        showSelectedLabCoursesCount = new javax.swing.JLabel();
        cse111CheckBox = new javax.swing.JCheckBox();
        cse112CheckBox = new javax.swing.JCheckBox();
        cse211CheckBox = new javax.swing.JCheckBox();
        cse212CheckBox = new javax.swing.JCheckBox();
        cse311CheckBox = new javax.swing.JCheckBox();
        cse312CheckBox = new javax.swing.JCheckBox();
        dropStudentPanel = new javax.swing.JPanel();
        dropSearchStudentPanel = new javax.swing.JPanel();
        jSeparator12 = new javax.swing.JSeparator();
        findStudentDropField = new javax.swing.JTextField();
        mainFromDrop1 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        dropStudentSearchButton1 = new javax.swing.JPanel();
        dropStudentSearchButtonLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dropFoundStudentPanel = new javax.swing.JPanel();
        mainFromDrop2 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        dropStudentSearchButton2 = new javax.swing.JPanel();
        dropStudentSearchButtonLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        resultPanel = new javax.swing.JPanel();
        resultSearchPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        resultSearchButton1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        mainFromResult1 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        resultSearchField1 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        resultViewPanel = new javax.swing.JPanel();
        mainFromResult4 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 47, 65));
        setForeground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomePanel.setBackground(new java.awt.Color(36, 47, 65));
        welcomePanel.setForeground(new java.awt.Color(204, 204, 204));
        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeText.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 255, 255));
        welcomeText.setText("Welcome to Student Database");
        welcomePanel.add(welcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 420, 50));

        findButton.setBackground(new java.awt.Color(50, 132, 255));
        findButton.setForeground(new java.awt.Color(255, 255, 255));
        findButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("FIND");
        findButton.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 40));

        welcomePanel.add(findButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 90, 40));
        welcomePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 330, 30));

        viewResultButton.setBackground(new java.awt.Color(36, 47, 65));
        viewResultButton.setForeground(new java.awt.Color(255, 255, 255));
        viewResultButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewResultButtonMouseClicked(evt);
            }
        });
        viewResultButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("RESULT");
        viewResultButton.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));
        viewResultButton.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 80, 20));

        welcomePanel.add(viewResultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 80, 50));

        admitStudentButton.setBackground(new java.awt.Color(36, 47, 65));
        admitStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        admitStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admitStudentButtonMouseClicked(evt);
            }
        });
        admitStudentButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("ADMIT");
        admitStudentButton.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));
        admitStudentButton.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 70, 20));

        welcomePanel.add(admitStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 70, 50));

        dropStudentButton.setBackground(new java.awt.Color(36, 47, 65));
        dropStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropStudentButtonMouseClicked(evt);
            }
        });
        dropStudentButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("EDIT OR DROP");
        dropStudentButton.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));
        dropStudentButton.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 20));

        welcomePanel.add(dropStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 140, 50));

        findStudentField.setBackground(new java.awt.Color(36, 47, 65));
        findStudentField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        findStudentField.setForeground(new java.awt.Color(204, 204, 204));
        findStudentField.setText("Enter ID to find");
        findStudentField.setBorder(null);
        findStudentField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findStudentFieldMouseClicked(evt);
            }
        });
        findStudentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findStudentFieldActionPerformed(evt);
            }
        });
        welcomePanel.add(findStudentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 330, 40));

        admitStudentButton1.setBackground(new java.awt.Color(36, 47, 65));
        admitStudentButton1.setForeground(new java.awt.Color(255, 255, 255));
        admitStudentButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admitStudentButton1MouseClicked(evt);
            }
        });
        admitStudentButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("UPDATE");
        admitStudentButton1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));
        admitStudentButton1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 20));

        welcomePanel.add(admitStudentButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 90, 50));

        add(welcomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        addStudentPanel.setBackground(new java.awt.Color(36, 47, 65));
        addStudentPanel.setForeground(new java.awt.Color(204, 204, 204));
        addStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("STUDENT DETAILS");
        addStudentPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jSeparator21.setOrientation(javax.swing.SwingConstants.VERTICAL);
        addStudentPanel.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 20, 390));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SELECT COURSES");
        addStudentPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        nameLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        nameLabel4.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel4.setText("FULL NAME");
        addStudentPanel.add(nameLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        addStudentFullName.setBackground(new java.awt.Color(36, 47, 65));
        addStudentFullName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addStudentFullName.setForeground(new java.awt.Color(204, 204, 204));
        addStudentFullName.setText("Enter name");
        addStudentFullName.setBorder(null);
        addStudentFullName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudentFullNameMouseClicked(evt);
            }
        });
        addStudentPanel.add(addStudentFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 40));
        addStudentPanel.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, -1));

        idLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        idLabel4.setForeground(new java.awt.Color(255, 255, 255));
        idLabel4.setText("ID");
        addStudentPanel.add(idLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        addStudentID.setBackground(new java.awt.Color(36, 47, 65));
        addStudentID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addStudentID.setForeground(new java.awt.Color(204, 204, 204));
        addStudentID.setText("Enter student ID");
        addStudentID.setBorder(null);
        addStudentID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudentIDMouseClicked(evt);
            }
        });
        addStudentPanel.add(addStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, 40));
        addStudentPanel.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, -1));

        addFathersNameField.setBackground(new java.awt.Color(36, 47, 65));
        addFathersNameField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addFathersNameField.setForeground(new java.awt.Color(204, 204, 204));
        addFathersNameField.setText("Enter name");
        addFathersNameField.setBorder(null);
        addFathersNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFathersNameFieldMouseClicked(evt);
            }
        });
        addStudentPanel.add(addFathersNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, 40));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("SELECTED COURSES:");
        addStudentPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));
        addStudentPanel.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 200, -1));

        genderLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        genderLabel4.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel4.setText("GENDER");
        addStudentPanel.add(genderLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));
        addStudentPanel.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 200, -1));

        motherLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        motherLabel4.setForeground(new java.awt.Color(255, 255, 255));
        motherLabel4.setText("MOTHER'S NAME");
        addStudentPanel.add(motherLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        addFemaleCheck.setBackground(new java.awt.Color(36, 47, 65));
        addFemaleCheck.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addFemaleCheck.setForeground(new java.awt.Color(255, 255, 255));
        addFemaleCheck.setText("FEMALE");
        addStudentPanel.add(addFemaleCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        addMaleCheck.setBackground(new java.awt.Color(36, 47, 65));
        addMaleCheck.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addMaleCheck.setForeground(new java.awt.Color(255, 255, 255));
        addMaleCheck.setText("MALE");
        addStudentPanel.add(addMaleCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        createProfileButtonPanel4.setBackground(new java.awt.Color(50, 132, 255));
        createProfileButtonPanel4.setForeground(new java.awt.Color(255, 255, 255));
        createProfileButtonPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createProfileButtonPanel4MouseClicked(evt);
            }
        });
        createProfileButtonPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("CREATE PROFILE");
        createProfileButtonPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 50));

        addStudentPanel.add(createProfileButtonPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 190, 50));

        showSelectedCoursesCount.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        showSelectedCoursesCount.setForeground(new java.awt.Color(255, 0, 102));
        showSelectedCoursesCount.setText("0");
        addStudentPanel.add(showSelectedCoursesCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 60, 40));

        addMothersNameField.setBackground(new java.awt.Color(36, 47, 65));
        addMothersNameField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addMothersNameField.setForeground(new java.awt.Color(204, 204, 204));
        addMothersNameField.setText("Enter name");
        addMothersNameField.setBorder(null);
        addMothersNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMothersNameFieldMouseClicked(evt);
            }
        });
        addStudentPanel.add(addMothersNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 200, 40));

        fatherLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        fatherLabel4.setForeground(new java.awt.Color(255, 255, 255));
        fatherLabel4.setText("FATHER'S NAME");
        addStudentPanel.add(fatherLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        mainFromAdmit.setBackground(new java.awt.Color(36, 47, 65));
        mainFromAdmit.setForeground(new java.awt.Color(255, 255, 255));
        mainFromAdmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromAdmitMouseClicked(evt);
            }
        });
        mainFromAdmit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("BACK TO MAIN MENU");
        mainFromAdmit.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 140, 40));
        mainFromAdmit.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 20));

        addStudentPanel.add(mainFromAdmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        cse101CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse101CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse101CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse101CheckBox.setText("CSE 101");
        cse101CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse101CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse101CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 90, 30));

        cse201CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse201CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse201CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse201CheckBox.setText("CSE 201");
        cse201CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse201CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse201CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 90, 30));

        cse301CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse301CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse301CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse301CheckBox.setText("CSE 301");
        cse301CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse301CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse301CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 90, 30));

        cse102CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse102CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse102CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse102CheckBox.setText("CSE 102");
        cse102CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse102CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse102CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 90, 30));

        cse202CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse202CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse202CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse202CheckBox.setText("CSE 202");
        cse202CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse202CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse202CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 90, 30));

        cse302CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse302CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse302CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse302CheckBox.setText("CSE 302");
        cse302CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse302CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse302CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 90, 30));

        cse103CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse103CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse103CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse103CheckBox.setText("CSE 103");
        cse103CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse103CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse103CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 90, 30));

        cse203CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse203CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse203CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse203CheckBox.setText("CSE 203");
        cse203CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse203CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse203CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 90, 30));

        cse303CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse303CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse303CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse303CheckBox.setText("CSE 303");
        cse303CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse303CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse303CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 90, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SELECT LAB COURSES");
        addStudentPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("SELECTED LAB COURSES:");
        addStudentPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        showSelectedLabCoursesCount.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        showSelectedLabCoursesCount.setForeground(new java.awt.Color(255, 0, 102));
        showSelectedLabCoursesCount.setText("0");
        addStudentPanel.add(showSelectedLabCoursesCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 100, 40));

        cse111CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse111CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse111CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse111CheckBox.setText("CSE 111");
        cse111CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse111CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse111CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 90, 30));

        cse112CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse112CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse112CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse112CheckBox.setText("CSE 112");
        cse112CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse112CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse112CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 90, 30));

        cse211CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse211CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse211CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse211CheckBox.setText("CSE 211");
        cse211CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse211CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse211CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 90, 30));

        cse212CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse212CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse212CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse212CheckBox.setText("CSE 212");
        cse212CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse212CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse212CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 90, 30));

        cse311CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse311CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse311CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse311CheckBox.setText("CSE 311");
        cse311CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse311CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse311CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 90, 30));

        cse312CheckBox.setBackground(new java.awt.Color(36, 47, 65));
        cse312CheckBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cse312CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cse312CheckBox.setText("CSE 312");
        cse312CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cse312CheckBoxActionPerformed(evt);
            }
        });
        addStudentPanel.add(cse312CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 90, 30));

        add(addStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dropStudentPanel.setBackground(new java.awt.Color(36, 47, 65));
        dropStudentPanel.setForeground(new java.awt.Color(204, 204, 204));
        dropStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropSearchStudentPanel.setBackground(new java.awt.Color(36, 47, 65));
        dropSearchStudentPanel.setForeground(new java.awt.Color(204, 204, 204));
        dropSearchStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        dropSearchStudentPanel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 330, 30));

        findStudentDropField.setBackground(new java.awt.Color(36, 47, 65));
        findStudentDropField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        findStudentDropField.setForeground(new java.awt.Color(204, 204, 204));
        findStudentDropField.setText("Enter Student ID");
        findStudentDropField.setBorder(null);
        findStudentDropField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findStudentDropFieldMouseClicked(evt);
            }
        });
        findStudentDropField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findStudentDropFieldActionPerformed(evt);
            }
        });
        dropSearchStudentPanel.add(findStudentDropField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 330, 40));

        mainFromDrop1.setBackground(new java.awt.Color(36, 47, 65));
        mainFromDrop1.setForeground(new java.awt.Color(255, 255, 255));
        mainFromDrop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromDrop1MouseClicked(evt);
            }
        });
        mainFromDrop1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("BACK TO MAIN MENU");
        mainFromDrop1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromDrop1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        dropSearchStudentPanel.add(mainFromDrop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        dropStudentSearchButton1.setBackground(new java.awt.Color(50, 132, 255));
        dropStudentSearchButton1.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentSearchButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropStudentSearchButtonLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        dropStudentSearchButtonLabel1.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentSearchButtonLabel1.setText("FIND");
        dropStudentSearchButton1.add(dropStudentSearchButtonLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 40));

        dropSearchStudentPanel.add(dropStudentSearchButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 90, 40));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Drop Student");
        dropSearchStudentPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 240, 40));

        dropStudentPanel.add(dropSearchStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dropFoundStudentPanel.setBackground(new java.awt.Color(36, 47, 65));
        dropFoundStudentPanel.setForeground(new java.awt.Color(204, 204, 204));
        dropFoundStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainFromDrop2.setBackground(new java.awt.Color(36, 47, 65));
        mainFromDrop2.setForeground(new java.awt.Color(255, 255, 255));
        mainFromDrop2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromDrop2MouseClicked(evt);
            }
        });
        mainFromDrop2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("BACK TO MAIN MENU");
        mainFromDrop2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromDrop2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        dropFoundStudentPanel.add(mainFromDrop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        dropStudentSearchButton2.setBackground(new java.awt.Color(50, 132, 255));
        dropStudentSearchButton2.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentSearchButton2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropStudentSearchButtonLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        dropStudentSearchButtonLabel2.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentSearchButtonLabel2.setText("PROCEED");
        dropStudentSearchButton2.add(dropStudentSearchButtonLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 40));

        dropFoundStudentPanel.add(dropStudentSearchButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 120, 40));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("DROP STUDENT");
        dropFoundStudentPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 190, 40));

        dropStudentPanel.add(dropFoundStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(dropStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        resultPanel.setBackground(new java.awt.Color(36, 47, 65));
        resultPanel.setForeground(new java.awt.Color(204, 204, 204));
        resultPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultSearchPanel.setBackground(new java.awt.Color(36, 47, 65));
        resultSearchPanel.setForeground(new java.awt.Color(204, 204, 204));
        resultSearchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Result");
        resultSearchPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 190, 40));

        resultSearchButton1.setBackground(new java.awt.Color(50, 132, 255));
        resultSearchButton1.setForeground(new java.awt.Color(255, 255, 255));
        resultSearchButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("RESULT");
        resultSearchButton1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 40));

        resultSearchPanel.add(resultSearchButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 100, 40));

        mainFromResult1.setBackground(new java.awt.Color(36, 47, 65));
        mainFromResult1.setForeground(new java.awt.Color(255, 255, 255));
        mainFromResult1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromResult1MouseClicked(evt);
            }
        });
        mainFromResult1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("BACK TO MAIN MENU");
        mainFromResult1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromResult1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        resultSearchPanel.add(mainFromResult1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        resultSearchField1.setBackground(new java.awt.Color(36, 47, 65));
        resultSearchField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        resultSearchField1.setForeground(new java.awt.Color(204, 204, 204));
        resultSearchField1.setText("Enter Student ID");
        resultSearchField1.setBorder(null);
        resultSearchField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultSearchField1MouseClicked(evt);
            }
        });
        resultSearchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultSearchField1ActionPerformed(evt);
            }
        });
        resultSearchPanel.add(resultSearchField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 330, 40));
        resultSearchPanel.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 330, 30));

        resultPanel.add(resultSearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        resultViewPanel.setBackground(new java.awt.Color(36, 47, 65));
        resultViewPanel.setForeground(new java.awt.Color(204, 204, 204));
        resultViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainFromResult4.setBackground(new java.awt.Color(36, 47, 65));
        mainFromResult4.setForeground(new java.awt.Color(255, 255, 255));
        mainFromResult4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromResult4MouseClicked(evt);
            }
        });
        mainFromResult4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("BACK TO MAIN MENU");
        mainFromResult4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromResult4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        resultViewPanel.add(mainFromResult4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Result");
        resultViewPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 190, 40));

        resultPanel.add(resultViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(resultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentFullNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentFullNameMouseClicked
        this.addStudentFullName.setText("");
    }//GEN-LAST:event_addStudentFullNameMouseClicked

    private void addStudentIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentIDMouseClicked
        this.addStudentID.setText("");
    }//GEN-LAST:event_addStudentIDMouseClicked

    private void addFathersNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFathersNameFieldMouseClicked
        this.addFathersNameField.setText("");
    }//GEN-LAST:event_addFathersNameFieldMouseClicked

    private void addMothersNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMothersNameFieldMouseClicked
       this.addMothersNameField.setText("");
    }//GEN-LAST:event_addMothersNameFieldMouseClicked

    private void viewResultButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResultButtonMouseClicked
        //Need to implement dynamic views after setting up search fucntion
        displayResultPanel(true, false);
    }//GEN-LAST:event_viewResultButtonMouseClicked

    private void admitStudentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admitStudentButtonMouseClicked
        panelVisiblity(false, true, false, false);
    }//GEN-LAST:event_admitStudentButtonMouseClicked

    private void mainFromAdmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromAdmitMouseClicked
        panelVisiblity(true, false, false, false); //DONE
    }//GEN-LAST:event_mainFromAdmitMouseClicked

    private void dropStudentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropStudentButtonMouseClicked
        //Need to implement dynamic views after setting up search fucntion
        displayDropStudentPanel(true, false);
    }//GEN-LAST:event_dropStudentButtonMouseClicked

    private void findStudentFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findStudentFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_findStudentFieldMouseClicked

    private void findStudentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findStudentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findStudentFieldActionPerformed

    private void findStudentDropFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findStudentDropFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_findStudentDropFieldMouseClicked

    private void findStudentDropFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findStudentDropFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findStudentDropFieldActionPerformed

    private void mainFromDrop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromDrop1MouseClicked
        panelVisiblity(true, false, false, false); //DONE
    }//GEN-LAST:event_mainFromDrop1MouseClicked

    private void mainFromDrop2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromDrop2MouseClicked
        panelVisiblity(true, false, false, false); //DONE
    }//GEN-LAST:event_mainFromDrop2MouseClicked

    private void mainFromResult1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromResult1MouseClicked
       panelVisiblity(true, false, false, false); //DONE
    }//GEN-LAST:event_mainFromResult1MouseClicked

    private void resultSearchField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultSearchField1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resultSearchField1MouseClicked

    private void resultSearchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultSearchField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultSearchField1ActionPerformed

    private void mainFromResult4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromResult4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mainFromResult4MouseClicked

    private void createProfileButtonPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createProfileButtonPanel4MouseClicked
        createStudentProfile();
    }//GEN-LAST:event_createProfileButtonPanel4MouseClicked

    //K THEN LET IT RAIN DATA
    //GOAL Have to find out a better way to do this without repeating all these codes
    private void cse101CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse101CheckBoxActionPerformed
        if(this.cse101CheckBox.isSelected() && this.mainCourseCount < 4) {
            this.courses.add(new Course(this.cse101CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 4) {
                this.showSelectedCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        } else if(this.mainCourseCount >= 4 && this.cse101CheckBox.isSelected()) {
            cse101CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse101CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        }
    }//GEN-LAST:event_cse101CheckBoxActionPerformed

    private void cse201CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse201CheckBoxActionPerformed
        if(this.cse201CheckBox.isSelected() && this.mainCourseCount < 4) {
            this.courses.add(new Course(this.cse201CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 4) {
                this.showSelectedCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        } else if(this.mainCourseCount >= 4 && this.cse201CheckBox.isSelected()) {
            cse201CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse201CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        }
    }//GEN-LAST:event_cse201CheckBoxActionPerformed

    private void cse301CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse301CheckBoxActionPerformed
        if(this.cse301CheckBox.isSelected() && this.mainCourseCount < 4) {
            this.courses.add(new Course(this.cse301CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 4) {
                this.showSelectedCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        } else if(this.mainCourseCount >= 4 && this.cse301CheckBox.isSelected()) {
            cse301CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse301CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        }
    }//GEN-LAST:event_cse301CheckBoxActionPerformed

    private void cse102CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse102CheckBoxActionPerformed
        if(this.cse102CheckBox.isSelected() && this.mainCourseCount < 4) {
            this.courses.add(new Course(this.cse102CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 4) {
                this.showSelectedCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        } else if(this.mainCourseCount >= 4 && this.cse102CheckBox.isSelected()) {
            cse102CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse102CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        }
    }//GEN-LAST:event_cse102CheckBoxActionPerformed

    private void cse202CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse202CheckBoxActionPerformed
        if(this.cse202CheckBox.isSelected() && this.mainCourseCount < 4) {
            this.courses.add(new Course(this.cse202CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 4) {
                this.showSelectedCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        } else if(this.mainCourseCount >= 4 && this.cse202CheckBox.isSelected()) {
            cse202CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse202CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        }
    }//GEN-LAST:event_cse202CheckBoxActionPerformed

    private void cse302CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse302CheckBoxActionPerformed
        if(this.cse302CheckBox.isSelected() && this.mainCourseCount < 4) {
            this.courses.add(new Course(this.cse302CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 4) {
                this.showSelectedCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        } else if(this.mainCourseCount >= 4 && this.cse302CheckBox.isSelected()) {
            cse302CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse302CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        }
    }//GEN-LAST:event_cse302CheckBoxActionPerformed

    private void cse103CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse103CheckBoxActionPerformed
        if(this.cse103CheckBox.isSelected() && this.mainCourseCount < 4) {
            this.courses.add(new Course(this.cse103CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 4) {
                this.showSelectedCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        } else if(this.mainCourseCount >= 4 && this.cse103CheckBox.isSelected()) {
            cse103CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse103CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        }
    }//GEN-LAST:event_cse103CheckBoxActionPerformed

    private void cse203CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse203CheckBoxActionPerformed
        if(this.cse203CheckBox.isSelected() && this.mainCourseCount < 4) {
            this.courses.add(new Course(this.cse203CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 4) {
                this.showSelectedCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        } else if(this.mainCourseCount >= 4 && this.cse203CheckBox.isSelected()) {
            cse203CheckBox.setSelected(false);
        }  else {
            deleteCourse(this.cse203CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        }
    }//GEN-LAST:event_cse203CheckBoxActionPerformed

    private void cse303CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse303CheckBoxActionPerformed
        if(this.cse303CheckBox.isSelected() && this.mainCourseCount < 4) {
            this.courses.add(new Course(this.cse303CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 4) {
                this.showSelectedCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        } else if(this.mainCourseCount >= 4 && this.cse303CheckBox.isSelected()) {
            cse303CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse303CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedCoursesCount.setForeground(Color.RED);
            this.showSelectedCoursesCount.setText(""+this.mainCourseCount);
        }
    }//GEN-LAST:event_cse303CheckBoxActionPerformed

    //Lab Checkboxes
    private void cse111CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse111CheckBoxActionPerformed
        if(this.cse111CheckBox.isSelected() && this.mainCourseCount < 6 && this.mainCourseCount >= 4) {
            this.courses.add(new Course(this.cse111CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 6) {
                this.showSelectedLabCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
            mainCourseEnabler(false);
        } else if((this.mainCourseCount < 4 || this.mainCourseCount >= 6) && this.cse111CheckBox.isSelected()) {
            cse111CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse111CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
        }
    }//GEN-LAST:event_cse111CheckBoxActionPerformed

    private void cse112CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse112CheckBoxActionPerformed
        if(this.cse112CheckBox.isSelected() && this.mainCourseCount < 6 && this.mainCourseCount >= 4) {
            this.courses.add(new Course(this.cse112CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 6) {
                this.showSelectedLabCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
            mainCourseEnabler(false);
        } else if((this.mainCourseCount < 4 || this.mainCourseCount >= 6) && this.cse112CheckBox.isSelected()) {
            cse112CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse112CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
        }
    }//GEN-LAST:event_cse112CheckBoxActionPerformed

    private void cse211CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse211CheckBoxActionPerformed
        if(this.cse211CheckBox.isSelected() && this.mainCourseCount < 6 && this.mainCourseCount >= 4) {
            this.courses.add(new Course(this.cse211CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 6) {
                this.showSelectedLabCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
            mainCourseEnabler(false);
        } else if((this.mainCourseCount < 4 || this.mainCourseCount >= 6) && this.cse211CheckBox.isSelected()) {
            cse211CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse211CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
        }
    }//GEN-LAST:event_cse211CheckBoxActionPerformed

    private void cse212CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse212CheckBoxActionPerformed
        if(this.cse212CheckBox.isSelected() && this.mainCourseCount < 6 && this.mainCourseCount >= 4) {
            this.courses.add(new Course(this.cse212CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 6) {
                this.showSelectedLabCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
            mainCourseEnabler(false);
        } else if((this.mainCourseCount < 4 || this.mainCourseCount >= 6) && this.cse212CheckBox.isSelected()) {
            cse212CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse212CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
        }
    }//GEN-LAST:event_cse212CheckBoxActionPerformed

    private void cse311CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse311CheckBoxActionPerformed
        if(this.cse311CheckBox.isSelected() && this.mainCourseCount < 6 && this.mainCourseCount >= 4) {
            this.courses.add(new Course(this.cse311CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            if(this.mainCourseCount == 6) {
                this.showSelectedLabCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
            mainCourseEnabler(false);
        } else if((this.mainCourseCount < 4 || this.mainCourseCount >= 6) && this.cse311CheckBox.isSelected()) {
            cse311CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse311CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
        }
    }//GEN-LAST:event_cse311CheckBoxActionPerformed

    private void cse312CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cse312CheckBoxActionPerformed
        if(this.cse312CheckBox.isSelected() && this.mainCourseCount < 6 && this.mainCourseCount >= 4) {
            this.courses.add(new Course(this.cse312CheckBox.getText(), 0.0));
            this.mainCourseCount++;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            if (this.mainCourseCount == 6) {
                this.showSelectedLabCoursesCount.setForeground(Color.GREEN);
            }
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
            mainCourseEnabler(false);
        } else if((this.mainCourseCount < 4 || this.mainCourseCount >= 6) && this.cse312CheckBox.isSelected()) {
            cse312CheckBox.setSelected(false);
        } else {
            deleteCourse(this.cse312CheckBox.getText());
            this.mainCourseCount--;
            this.showSelectedLabCoursesCount.setForeground(Color.RED);
            this.showSelectedLabCoursesCount.setText(""+(this.mainCourseCount-4));
        }
    }//GEN-LAST:event_cse312CheckBoxActionPerformed

    private void admitStudentButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admitStudentButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_admitStudentButton1MouseClicked
    
    //This function disables the main course checkboxes
    
    private void mainCourseEnabler(boolean value) {
        this.cse101CheckBox.setEnabled(value);
        this.cse102CheckBox.setEnabled(value);
        this.cse103CheckBox.setEnabled(value);
        this.cse201CheckBox.setEnabled(value);
        this.cse202CheckBox.setEnabled(value);
        this.cse203CheckBox.setEnabled(value);
        this.cse301CheckBox.setEnabled(value);
        this.cse302CheckBox.setEnabled(value);
        this.cse303CheckBox.setEnabled(value);
    }
    
    //This fucntion finds the index number of a Course array
    private void deleteCourse(String courseName) {
        for(int i = 0; i < this.courses.size(); i++) {
            if(this.courses.get(i).getCourseName().equals(courseName)) {
                this.courses.remove(i);
                return;
            }
        }
    }
    
    
    //Moar data, unverified
    
    private boolean addStudentInputERRPRN() {
        String fullName = this.addStudentFullName.getText();
        String id = this.addStudentID.getText();
        String fathersName = this.addFathersNameField.getText();
        String mothersName = this.addMothersNameField.getText();
        boolean verifiedFullName = checkFullName(fullName);
        boolean verifiedID = checkIdNum(id);
        boolean verifiedFathersName = checkFatherName(fathersName);
        boolean verifiedMothersName = checkMotherName(mothersName);
        if(this.addMaleCheck.isSelected() || this.addFemaleCheck.isSelected()) {
            if (this.addMaleCheck.isSelected()) {
                String gender = this.addMaleCheck.getText().toString();
                gender = gender.substring(0,1).toUpperCase() + gender.substring(1);
                this.student.setGender(gender);
            }
            if (this.addFemaleCheck.isSelected()) {
                String gender = this.addFemaleCheck.getText().toString();
                gender = gender.substring(0,1).toUpperCase() + gender.substring(1);
                this.student.setGender(gender);
            }
        } else {
            errorDialogue("Enter student's gender!", -1);
        }
        if (!verifiedFullName) {
            errorDialogue("Enter student's full name!", 0);
        }
        if (!verifiedID) {
            errorDialogue("Please enter the ID in correct format!\n" +
                               "        Format: 171-15-XXXX", 1);
        }
        if (!verifiedFathersName) {
            errorDialogue("Enter student's father's name!", 2);
        }
        if (!verifiedMothersName) {
            errorDialogue("Enter student's mother's name!", 3);
        }
        if(verifiedFullName && verifiedID && verifiedFathersName && verifiedMothersName) {
            this.student.setIdNum(id);
            this.student.setFullName(fullName);
            this.student.setMotherName(mothersName);
            this.student.setFatherName(fathersName);
            return true;
        }
        return false;
    }
    
    private boolean checkIdNum(String idNum) {
        if(idNum.length() == 11) {
            if(Objects.equals(idNum.substring(0, 1), "1") && Objects.equals(idNum.substring(1, 2), "7")  && Objects.equals(idNum.substring(2, 3), "1") && Objects.equals(idNum.substring(3, 4), "-") && Objects.equals(idNum.substring(4, 5), "1") && Objects.equals(idNum.substring(5, 6), "5") && Objects.equals(idNum.substring(6, 7), "-")) {
                return true;
            }
        }
        return false;
    }
    private boolean checkFullName(String fullName) {
        if(!fullName.equals("")) {
            return true;
        }
        return false;
    }
    
    private boolean checkFatherName(String fatherName) {
        if(!fatherName.equals("")) {
            return true;
        }
        return false;
    }
        
    private boolean checkMotherName(String motherName) {
        if(!motherName.equals("")) {
            return true;
        }
        return false;
    }
    
    private void errorDialogue(String messageString, int whichField) {
        Object[] message = {messageString};
        Object[] options = {"OK"};
        int n = JOptionPane.showOptionDialog(new JFrame(),
                message, "Alert!",
                JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null,
                options, options[0]);
        if(n == JOptionPane.ERROR_MESSAGE && whichField == 0){
            this.addStudentFullName.setText("");
        } else if(n == JOptionPane.ERROR_MESSAGE && whichField == 1){
            this.addStudentID.setText("171-15-XXXX");
        } else if(n == JOptionPane.ERROR_MESSAGE && whichField == 2){
            this.addFathersNameField.setText("");
        } else if(n == JOptionPane.ERROR_MESSAGE && whichField == 3){
            this.addMothersNameField.setText("");
        } else {
            //DO NOTHING JUST DISPLAY MESSAGE
        }
    }
    
    private boolean addCourseData() {
        if(this.courses.size()==6) {
            this.student.setA(new Course(this.courses.get(0).getCourseName(), this.courses.get(0).getGradePoints()));
            this.student.setB(new Course(this.courses.get(1).getCourseName(), this.courses.get(1).getGradePoints()));
            this.student.setC(new Course(this.courses.get(2).getCourseName(), this.courses.get(2).getGradePoints()));
            this.student.setD(new Course(this.courses.get(3).getCourseName(), this.courses.get(3).getGradePoints()));
            this.student.setE(new Course(this.courses.get(4).getCourseName(), this.courses.get(4).getGradePoints()));
            this.student.setF(new Course(this.courses.get(5).getCourseName(), this.courses.get(5).getGradePoints()));
            return true;
        } else {
            return false;
        }
    }
    
    private void createStudentProfile() {
        if(addStudentInputERRPRN() && addCourseData()) {
            addStudent();
            saveStudentData();
            refreshData();
        }
    }

    //These methods are for adding, dropping students and saving data
    private void addStudent() {
        this.students.add(this.student);
    }

    private void refreshData() {
        this.students = new ArrayList();
        this.student = new Student();
        this.courses = new ArrayList<>(6);
        this.mainCourseCount = 0;
    }
    
    private void dropStudent(int index) {
        this.students.remove(index);
    }
    
    private void saveStudentData() {
        try {
            FileOutputStream fos = new FileOutputStream("student.dat");
            ObjectOutputStream oos = new ObjectOutputStream(fos);   
            oos.writeObject(this.students); // write students to ObjectOutputStream
            oos.close(); 
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void loadStudentData() {
        try {
            FileInputStream fis = new FileInputStream("student.dat");
            ObjectInputStream ois = new ObjectInputStream(fis); 
            this.students = (ArrayList<Student>) ois.readObject(); // write students from ObjectInputStream to this.students
            ois.close();
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    private boolean checkSaveFile() {
        Path path = Paths.get("student.dat");

        if (Files.exists(path)) {
            System.out.println("Exists");
            return true;
        } else if (Files.notExists(path)) {
            return false;
        } else {
            return false;
        }
    }
    
    //These methods are for displaying the Drop Student Panel  
    private void displayDropStudentPanel(boolean search, boolean found) {
        panelVisiblity(false,false, true, false);
        this.dropSearchStudentPanel.setVisible(search);
        this.dropFoundStudentPanel.setVisible(found);
    }
    
    //These methods are for displaying the Result Panel  
    private void displayResultPanel(boolean search, boolean view) {
        panelVisiblity(false,false, false, true);
        this.resultSearchPanel.setVisible(search);
        this.resultViewPanel.setVisible(view);
    }
    
    //This method shows one panel at a time on screen
    private void panelVisiblity(boolean welcomePanel, boolean addStudentPanel, boolean dropStudentPanel, boolean viewResultPanel){
        this.welcomePanel.setVisible(welcomePanel);
        this.addStudentPanel.setVisible(addStudentPanel);
        this.dropStudentPanel.setVisible(dropStudentPanel);
        this.resultPanel.setVisible(viewResultPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addFathersNameField;
    private javax.swing.JRadioButton addFemaleCheck;
    private javax.swing.JRadioButton addMaleCheck;
    private javax.swing.JTextField addMothersNameField;
    private javax.swing.JTextField addStudentFullName;
    private javax.swing.JTextField addStudentID;
    private javax.swing.JPanel addStudentPanel;
    private javax.swing.JPanel admitStudentButton;
    private javax.swing.JPanel admitStudentButton1;
    private javax.swing.JPanel createProfileButtonPanel4;
    private javax.swing.JCheckBox cse101CheckBox;
    private javax.swing.JCheckBox cse102CheckBox;
    private javax.swing.JCheckBox cse103CheckBox;
    private javax.swing.JCheckBox cse111CheckBox;
    private javax.swing.JCheckBox cse112CheckBox;
    private javax.swing.JCheckBox cse201CheckBox;
    private javax.swing.JCheckBox cse202CheckBox;
    private javax.swing.JCheckBox cse203CheckBox;
    private javax.swing.JCheckBox cse211CheckBox;
    private javax.swing.JCheckBox cse212CheckBox;
    private javax.swing.JCheckBox cse301CheckBox;
    private javax.swing.JCheckBox cse302CheckBox;
    private javax.swing.JCheckBox cse303CheckBox;
    private javax.swing.JCheckBox cse311CheckBox;
    private javax.swing.JCheckBox cse312CheckBox;
    private javax.swing.JPanel dropFoundStudentPanel;
    private javax.swing.JPanel dropSearchStudentPanel;
    private javax.swing.JPanel dropStudentButton;
    private javax.swing.JPanel dropStudentPanel;
    private javax.swing.JPanel dropStudentSearchButton1;
    private javax.swing.JPanel dropStudentSearchButton2;
    private javax.swing.JLabel dropStudentSearchButtonLabel1;
    private javax.swing.JLabel dropStudentSearchButtonLabel2;
    private javax.swing.JLabel fatherLabel4;
    private javax.swing.JPanel findButton;
    private javax.swing.JTextField findStudentDropField;
    private javax.swing.JTextField findStudentField;
    private javax.swing.JLabel genderLabel4;
    private javax.swing.JLabel idLabel4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel mainFromAdmit;
    private javax.swing.JPanel mainFromDrop1;
    private javax.swing.JPanel mainFromDrop2;
    private javax.swing.JPanel mainFromResult1;
    private javax.swing.JPanel mainFromResult4;
    private javax.swing.JLabel motherLabel4;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JPanel resultSearchButton1;
    private javax.swing.JTextField resultSearchField1;
    private javax.swing.JPanel resultSearchPanel;
    private javax.swing.JPanel resultViewPanel;
    private javax.swing.JLabel showSelectedCoursesCount;
    private javax.swing.JLabel showSelectedLabCoursesCount;
    private javax.swing.JPanel viewResultButton;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
