/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd.edu.daffodilvarsity.studentdatabase;


/**
 *
 * @author Mushfiqus Salehin
 */
public class AddPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPanel
     */
    public AddPanel() {
        initComponents();
        panelVisiblity(true, false, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        addButtonPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        viewResultButton = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        admitStudentButton = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        dropStudentButton = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        addStudentPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        nameLabel4 = new javax.swing.JLabel();
        nameField4 = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        idLabel4 = new javax.swing.JLabel();
        idField4 = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        fathersNameField4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        genderLabel4 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList10 = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList11 = new javax.swing.JList<>();
        motherLabel4 = new javax.swing.JLabel();
        femaleCheck4 = new javax.swing.JRadioButton();
        maleCheck4 = new javax.swing.JRadioButton();
        createProfileButtonPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        addButtonPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        showSelectedCourses4 = new javax.swing.JLabel();
        mothersNameField4 = new javax.swing.JTextField();
        fatherLabel4 = new javax.swing.JLabel();
        mainFromAdmit = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        addButtonPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        dropStudentPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator36 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        nameLabel7 = new javax.swing.JLabel();
        nameField7 = new javax.swing.JTextField();
        jSeparator37 = new javax.swing.JSeparator();
        idLabel7 = new javax.swing.JLabel();
        idField7 = new javax.swing.JTextField();
        jSeparator38 = new javax.swing.JSeparator();
        fathersNameField7 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jSeparator39 = new javax.swing.JSeparator();
        genderLabel7 = new javax.swing.JLabel();
        jSeparator40 = new javax.swing.JSeparator();
        jScrollPane16 = new javax.swing.JScrollPane();
        jList16 = new javax.swing.JList<>();
        jScrollPane17 = new javax.swing.JScrollPane();
        jList17 = new javax.swing.JList<>();
        motherLabel7 = new javax.swing.JLabel();
        femaleCheck7 = new javax.swing.JRadioButton();
        maleCheck7 = new javax.swing.JRadioButton();
        removeButtonPanel7 = new javax.swing.JPanel();
        createProfileButtonPanel12 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        addButtonPanel7 = new javax.swing.JPanel();
        showSelectedCourses7 = new javax.swing.JLabel();
        mothersNameField7 = new javax.swing.JTextField();
        fatherLabel7 = new javax.swing.JLabel();
        mainFromDrop = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        viewResultPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        nameLabel6 = new javax.swing.JLabel();
        nameField6 = new javax.swing.JTextField();
        jSeparator32 = new javax.swing.JSeparator();
        idLabel6 = new javax.swing.JLabel();
        idField6 = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        fathersNameField6 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        genderLabel6 = new javax.swing.JLabel();
        jSeparator35 = new javax.swing.JSeparator();
        jScrollPane14 = new javax.swing.JScrollPane();
        jList14 = new javax.swing.JList<>();
        jScrollPane15 = new javax.swing.JScrollPane();
        jList15 = new javax.swing.JList<>();
        motherLabel6 = new javax.swing.JLabel();
        femaleCheck6 = new javax.swing.JRadioButton();
        maleCheck6 = new javax.swing.JRadioButton();
        removeButtonPanel6 = new javax.swing.JPanel();
        createProfileButtonPanel6 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        addButtonPanel6 = new javax.swing.JPanel();
        showSelectedCourses6 = new javax.swing.JLabel();
        mothersNameField6 = new javax.swing.JTextField();
        fatherLabel6 = new javax.swing.JLabel();
        mainFromResult = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(36, 47, 65));
        setForeground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomePanel.setBackground(new java.awt.Color(36, 47, 65));
        welcomePanel.setForeground(new java.awt.Color(204, 204, 204));
        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeText.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 255, 255));
        welcomeText.setText("Welcome to Student Database");
        welcomePanel.add(welcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 360, 50));

        addButtonPanel3.setBackground(new java.awt.Color(50, 132, 255));
        addButtonPanel3.setForeground(new java.awt.Color(255, 255, 255));
        addButtonPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("FIND");
        addButtonPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        welcomePanel.add(addButtonPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 100, 40));
        welcomePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 330, 30));

        viewResultButton.setBackground(new java.awt.Color(36, 47, 65));
        viewResultButton.setForeground(new java.awt.Color(255, 255, 255));
        viewResultButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewResultButtonMouseClicked(evt);
            }
        });
        viewResultButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("VIEW RESULT");
        viewResultButton.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 50));
        viewResultButton.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 20));

        welcomePanel.add(viewResultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 180, 50));

        admitStudentButton.setBackground(new java.awt.Color(36, 47, 65));
        admitStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        admitStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admitStudentButtonMouseClicked(evt);
            }
        });
        admitStudentButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("ADMIT STUDENT");
        admitStudentButton.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        admitStudentButton.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 20));

        welcomePanel.add(admitStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 170, 50));

        dropStudentButton.setBackground(new java.awt.Color(36, 47, 65));
        dropStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropStudentButtonMouseClicked(evt);
            }
        });
        dropStudentButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("DROP STUDENT");
        dropStudentButton.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        dropStudentButton.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        welcomePanel.add(dropStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 180, 50));

        add(welcomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        addStudentPanel.setBackground(new java.awt.Color(36, 47, 65));
        addStudentPanel.setForeground(new java.awt.Color(204, 204, 204));
        addStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("STUDENT DETAILS");
        addStudentPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jSeparator21.setOrientation(javax.swing.SwingConstants.VERTICAL);
        addStudentPanel.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 20, 390));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SELECT COURSES");
        addStudentPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        nameLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        nameLabel4.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel4.setText("FULL NAME");
        addStudentPanel.add(nameLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        nameField4.setBackground(new java.awt.Color(36, 47, 65));
        nameField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nameField4.setForeground(new java.awt.Color(204, 204, 204));
        nameField4.setText("Enter name");
        nameField4.setBorder(null);
        nameField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameField4MouseClicked(evt);
            }
        });
        nameField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameField4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(nameField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 40));
        addStudentPanel.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, -1));

        idLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        idLabel4.setForeground(new java.awt.Color(255, 255, 255));
        idLabel4.setText("ID");
        addStudentPanel.add(idLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        idField4.setBackground(new java.awt.Color(36, 47, 65));
        idField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        idField4.setForeground(new java.awt.Color(204, 204, 204));
        idField4.setText("Enter student ID");
        idField4.setBorder(null);
        idField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idField4MouseClicked(evt);
            }
        });
        idField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idField4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(idField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, 40));
        addStudentPanel.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, -1));

        fathersNameField4.setBackground(new java.awt.Color(36, 47, 65));
        fathersNameField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        fathersNameField4.setForeground(new java.awt.Color(204, 204, 204));
        fathersNameField4.setText("Enter name");
        fathersNameField4.setBorder(null);
        fathersNameField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fathersNameField4MouseClicked(evt);
            }
        });
        fathersNameField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathersNameField4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(fathersNameField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, 40));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("SELECTED COURSES:");
        addStudentPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));
        addStudentPanel.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 200, -1));

        genderLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        genderLabel4.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel4.setText("GENDER");
        addStudentPanel.add(genderLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));
        addStudentPanel.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 200, -1));

        jList10.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CSE121", "CSE 122", "CSE 123", "CSE 221", "CSE 222", "CSE 223" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(jList10);

        addStudentPanel.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 110, 230));

        jList11.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CSE121", "CSE 122", "CSE 123", "CSE 221", "CSE 222", "CSE 223" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(jList11);

        addStudentPanel.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 120, 230));

        motherLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        motherLabel4.setForeground(new java.awt.Color(255, 255, 255));
        motherLabel4.setText("MOTHER'S NAME");
        addStudentPanel.add(motherLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        femaleCheck4.setBackground(new java.awt.Color(36, 47, 65));
        femaleCheck4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        femaleCheck4.setForeground(new java.awt.Color(255, 255, 255));
        femaleCheck4.setText("FEMALE");
        femaleCheck4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleCheck4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(femaleCheck4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        maleCheck4.setBackground(new java.awt.Color(36, 47, 65));
        maleCheck4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        maleCheck4.setForeground(new java.awt.Color(255, 255, 255));
        maleCheck4.setText("MALE");
        maleCheck4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleCheck4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(maleCheck4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        createProfileButtonPanel4.setBackground(new java.awt.Color(50, 132, 255));
        createProfileButtonPanel4.setForeground(new java.awt.Color(255, 255, 255));
        createProfileButtonPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("CREATE PROFILE");
        createProfileButtonPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 30));

        addStudentPanel.add(createProfileButtonPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 180, 50));

        addButtonPanel4.setBackground(new java.awt.Color(255, 52, 36));
        addButtonPanel4.setForeground(new java.awt.Color(255, 255, 255));
        addButtonPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("<<REMOVE");
        addButtonPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 80, -1));

        addStudentPanel.add(addButtonPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 90, 40));

        showSelectedCourses4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        showSelectedCourses4.setForeground(new java.awt.Color(255, 0, 102));
        showSelectedCourses4.setText("0");
        addStudentPanel.add(showSelectedCourses4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 70, 20));

        mothersNameField4.setBackground(new java.awt.Color(36, 47, 65));
        mothersNameField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        mothersNameField4.setForeground(new java.awt.Color(204, 204, 204));
        mothersNameField4.setText("Enter name");
        mothersNameField4.setBorder(null);
        mothersNameField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mothersNameField4MouseClicked(evt);
            }
        });
        mothersNameField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothersNameField4ActionPerformed(evt);
            }
        });
        addStudentPanel.add(mothersNameField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 200, 40));

        fatherLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        fatherLabel4.setForeground(new java.awt.Color(255, 255, 255));
        fatherLabel4.setText("FATHER'S NAME");
        addStudentPanel.add(fatherLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        mainFromAdmit.setBackground(new java.awt.Color(36, 47, 65));
        mainFromAdmit.setForeground(new java.awt.Color(255, 255, 255));
        mainFromAdmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromAdmitMouseClicked(evt);
            }
        });
        mainFromAdmit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("BACK TO MAIN MENU");
        mainFromAdmit.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromAdmit.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 20));

        addStudentPanel.add(mainFromAdmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        addButtonPanel5.setBackground(new java.awt.Color(38, 177, 76));
        addButtonPanel5.setForeground(new java.awt.Color(255, 255, 255));
        addButtonPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("ADD>>");
        addButtonPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 50, -1));

        addStudentPanel.add(addButtonPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 90, 40));

        add(addStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dropStudentPanel.setBackground(new java.awt.Color(36, 47, 65));
        dropStudentPanel.setForeground(new java.awt.Color(204, 204, 204));
        dropStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("STUDENT DETAILS");
        dropStudentPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jSeparator36.setOrientation(javax.swing.SwingConstants.VERTICAL);
        dropStudentPanel.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 20, 390));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("SELECT COURSES");
        dropStudentPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        nameLabel7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        nameLabel7.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel7.setText("FULL NAME");
        dropStudentPanel.add(nameLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        nameField7.setBackground(new java.awt.Color(36, 47, 65));
        nameField7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nameField7.setForeground(new java.awt.Color(204, 204, 204));
        nameField7.setText("Enter name");
        nameField7.setBorder(null);
        nameField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameField7MouseClicked(evt);
            }
        });
        nameField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameField7ActionPerformed(evt);
            }
        });
        dropStudentPanel.add(nameField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 40));
        dropStudentPanel.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, -1));

        idLabel7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        idLabel7.setForeground(new java.awt.Color(255, 255, 255));
        idLabel7.setText("ID");
        dropStudentPanel.add(idLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        idField7.setBackground(new java.awt.Color(36, 47, 65));
        idField7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        idField7.setForeground(new java.awt.Color(204, 204, 204));
        idField7.setText("Enter student ID");
        idField7.setBorder(null);
        idField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idField7MouseClicked(evt);
            }
        });
        idField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idField7ActionPerformed(evt);
            }
        });
        dropStudentPanel.add(idField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, 40));
        dropStudentPanel.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, -1));

        fathersNameField7.setBackground(new java.awt.Color(36, 47, 65));
        fathersNameField7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        fathersNameField7.setForeground(new java.awt.Color(204, 204, 204));
        fathersNameField7.setText("Enter name");
        fathersNameField7.setBorder(null);
        fathersNameField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fathersNameField7MouseClicked(evt);
            }
        });
        fathersNameField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathersNameField7ActionPerformed(evt);
            }
        });
        dropStudentPanel.add(fathersNameField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, 40));

        jLabel42.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("SELECTED COURSES:");
        dropStudentPanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));
        dropStudentPanel.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 200, -1));

        genderLabel7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        genderLabel7.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel7.setText("GENDER");
        dropStudentPanel.add(genderLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));
        dropStudentPanel.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 200, -1));

        jList16.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CSE121", "CSE 122", "CSE 123", "CSE 221", "CSE 222", "CSE 223" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane16.setViewportView(jList16);

        dropStudentPanel.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 110, 230));

        jList17.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CSE121", "CSE 122", "CSE 123", "CSE 221", "CSE 222", "CSE 223" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane17.setViewportView(jList17);

        dropStudentPanel.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 120, 230));

        motherLabel7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        motherLabel7.setForeground(new java.awt.Color(255, 255, 255));
        motherLabel7.setText("MOTHER'S NAME");
        dropStudentPanel.add(motherLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        femaleCheck7.setBackground(new java.awt.Color(36, 47, 65));
        femaleCheck7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        femaleCheck7.setForeground(new java.awt.Color(255, 255, 255));
        femaleCheck7.setText("FEMALE");
        femaleCheck7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleCheck7ActionPerformed(evt);
            }
        });
        dropStudentPanel.add(femaleCheck7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        maleCheck7.setBackground(new java.awt.Color(36, 47, 65));
        maleCheck7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        maleCheck7.setForeground(new java.awt.Color(255, 255, 255));
        maleCheck7.setText("MALE");
        maleCheck7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleCheck7ActionPerformed(evt);
            }
        });
        dropStudentPanel.add(maleCheck7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        removeButtonPanel7.setBackground(new java.awt.Color(50, 132, 255));
        removeButtonPanel7.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentPanel.add(removeButtonPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 90, 40));

        createProfileButtonPanel12.setBackground(new java.awt.Color(50, 132, 255));
        createProfileButtonPanel12.setForeground(new java.awt.Color(255, 255, 255));
        createProfileButtonPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("CREATE PROFILE");
        createProfileButtonPanel12.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 30));

        dropStudentPanel.add(createProfileButtonPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 180, 50));

        addButtonPanel7.setBackground(new java.awt.Color(50, 132, 255));
        addButtonPanel7.setForeground(new java.awt.Color(255, 255, 255));
        dropStudentPanel.add(addButtonPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 90, 40));

        showSelectedCourses7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        showSelectedCourses7.setForeground(new java.awt.Color(255, 0, 102));
        showSelectedCourses7.setText("0");
        dropStudentPanel.add(showSelectedCourses7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 70, 20));

        mothersNameField7.setBackground(new java.awt.Color(36, 47, 65));
        mothersNameField7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        mothersNameField7.setForeground(new java.awt.Color(204, 204, 204));
        mothersNameField7.setText("Enter name");
        mothersNameField7.setBorder(null);
        mothersNameField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mothersNameField7MouseClicked(evt);
            }
        });
        mothersNameField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothersNameField7ActionPerformed(evt);
            }
        });
        dropStudentPanel.add(mothersNameField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 200, 40));

        fatherLabel7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        fatherLabel7.setForeground(new java.awt.Color(255, 255, 255));
        fatherLabel7.setText("FATHER'S NAME");
        dropStudentPanel.add(fatherLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        mainFromDrop.setBackground(new java.awt.Color(36, 47, 65));
        mainFromDrop.setForeground(new java.awt.Color(255, 255, 255));
        mainFromDrop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromDropMouseClicked(evt);
            }
        });
        mainFromDrop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("BACK TO MAIN MENU");
        mainFromDrop.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromDrop.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 20));

        dropStudentPanel.add(mainFromDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        add(dropStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        viewResultPanel.setBackground(new java.awt.Color(36, 47, 65));
        viewResultPanel.setForeground(new java.awt.Color(204, 204, 204));
        viewResultPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("STUDENT DETAILS");
        viewResultPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jSeparator31.setOrientation(javax.swing.SwingConstants.VERTICAL);
        viewResultPanel.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 20, 390));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SELECT COURSES");
        viewResultPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        nameLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        nameLabel6.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel6.setText("FULL NAME");
        viewResultPanel.add(nameLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        nameField6.setBackground(new java.awt.Color(36, 47, 65));
        nameField6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nameField6.setForeground(new java.awt.Color(204, 204, 204));
        nameField6.setText("Enter name");
        nameField6.setBorder(null);
        nameField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameField6MouseClicked(evt);
            }
        });
        nameField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameField6ActionPerformed(evt);
            }
        });
        viewResultPanel.add(nameField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 40));
        viewResultPanel.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, -1));

        idLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        idLabel6.setForeground(new java.awt.Color(255, 255, 255));
        idLabel6.setText("ID");
        viewResultPanel.add(idLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        idField6.setBackground(new java.awt.Color(36, 47, 65));
        idField6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        idField6.setForeground(new java.awt.Color(204, 204, 204));
        idField6.setText("Enter student ID");
        idField6.setBorder(null);
        idField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idField6MouseClicked(evt);
            }
        });
        idField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idField6ActionPerformed(evt);
            }
        });
        viewResultPanel.add(idField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, 40));
        viewResultPanel.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, -1));

        fathersNameField6.setBackground(new java.awt.Color(36, 47, 65));
        fathersNameField6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        fathersNameField6.setForeground(new java.awt.Color(204, 204, 204));
        fathersNameField6.setText("Enter name");
        fathersNameField6.setBorder(null);
        fathersNameField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fathersNameField6MouseClicked(evt);
            }
        });
        fathersNameField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathersNameField6ActionPerformed(evt);
            }
        });
        viewResultPanel.add(fathersNameField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, 40));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("SELECTED COURSES:");
        viewResultPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));
        viewResultPanel.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 200, -1));

        genderLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        genderLabel6.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel6.setText("GENDER");
        viewResultPanel.add(genderLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));
        viewResultPanel.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 200, -1));

        jList14.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CSE121", "CSE 122", "CSE 123", "CSE 221", "CSE 222", "CSE 223" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane14.setViewportView(jList14);

        viewResultPanel.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 110, 230));

        jList15.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CSE121", "CSE 122", "CSE 123", "CSE 221", "CSE 222", "CSE 223" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane15.setViewportView(jList15);

        viewResultPanel.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 120, 230));

        motherLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        motherLabel6.setForeground(new java.awt.Color(255, 255, 255));
        motherLabel6.setText("MOTHER'S NAME");
        viewResultPanel.add(motherLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        femaleCheck6.setBackground(new java.awt.Color(36, 47, 65));
        femaleCheck6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        femaleCheck6.setForeground(new java.awt.Color(255, 255, 255));
        femaleCheck6.setText("FEMALE");
        femaleCheck6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleCheck6ActionPerformed(evt);
            }
        });
        viewResultPanel.add(femaleCheck6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        maleCheck6.setBackground(new java.awt.Color(36, 47, 65));
        maleCheck6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        maleCheck6.setForeground(new java.awt.Color(255, 255, 255));
        maleCheck6.setText("MALE");
        maleCheck6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleCheck6ActionPerformed(evt);
            }
        });
        viewResultPanel.add(maleCheck6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        removeButtonPanel6.setBackground(new java.awt.Color(50, 132, 255));
        removeButtonPanel6.setForeground(new java.awt.Color(255, 255, 255));
        viewResultPanel.add(removeButtonPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 90, 40));

        createProfileButtonPanel6.setBackground(new java.awt.Color(50, 132, 255));
        createProfileButtonPanel6.setForeground(new java.awt.Color(255, 255, 255));
        createProfileButtonPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("CREATE PROFILE");
        createProfileButtonPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 30));

        viewResultPanel.add(createProfileButtonPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 180, 50));

        addButtonPanel6.setBackground(new java.awt.Color(50, 132, 255));
        addButtonPanel6.setForeground(new java.awt.Color(255, 255, 255));
        viewResultPanel.add(addButtonPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 90, 40));

        showSelectedCourses6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        showSelectedCourses6.setForeground(new java.awt.Color(255, 0, 102));
        showSelectedCourses6.setText("0");
        viewResultPanel.add(showSelectedCourses6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 70, 20));

        mothersNameField6.setBackground(new java.awt.Color(36, 47, 65));
        mothersNameField6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        mothersNameField6.setForeground(new java.awt.Color(204, 204, 204));
        mothersNameField6.setText("Enter name");
        mothersNameField6.setBorder(null);
        mothersNameField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mothersNameField6MouseClicked(evt);
            }
        });
        mothersNameField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothersNameField6ActionPerformed(evt);
            }
        });
        viewResultPanel.add(mothersNameField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 200, 40));

        fatherLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        fatherLabel6.setForeground(new java.awt.Color(255, 255, 255));
        fatherLabel6.setText("FATHER'S NAME");
        viewResultPanel.add(fatherLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        mainFromResult.setBackground(new java.awt.Color(36, 47, 65));
        mainFromResult.setForeground(new java.awt.Color(255, 255, 255));
        mainFromResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainFromResultMouseClicked(evt);
            }
        });
        mainFromResult.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("BACK TO MAIN MENU");
        mainFromResult.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 50));
        mainFromResult.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 20));

        viewResultPanel.add(mainFromResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 170, 50));

        add(viewResultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField4MouseClicked

    private void nameField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField4ActionPerformed

    private void idField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idField4MouseClicked

    private void idField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idField4ActionPerformed

    private void fathersNameField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fathersNameField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fathersNameField4MouseClicked

    private void fathersNameField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathersNameField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathersNameField4ActionPerformed

    private void femaleCheck4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleCheck4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleCheck4ActionPerformed

    private void maleCheck4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleCheck4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleCheck4ActionPerformed

    private void mothersNameField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mothersNameField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mothersNameField4MouseClicked

    private void mothersNameField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothersNameField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothersNameField4ActionPerformed

    private void nameField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameField6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField6MouseClicked

    private void nameField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField6ActionPerformed

    private void idField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idField6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idField6MouseClicked

    private void idField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idField6ActionPerformed

    private void fathersNameField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fathersNameField6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fathersNameField6MouseClicked

    private void fathersNameField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathersNameField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathersNameField6ActionPerformed

    private void femaleCheck6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleCheck6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleCheck6ActionPerformed

    private void maleCheck6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleCheck6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleCheck6ActionPerformed

    private void mothersNameField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mothersNameField6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mothersNameField6MouseClicked

    private void mothersNameField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothersNameField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothersNameField6ActionPerformed

    private void admitStudentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admitStudentButtonMouseClicked
        // TODO add your handling code here:
        panelVisiblity(false, true, false, false);
    }//GEN-LAST:event_admitStudentButtonMouseClicked

    private void viewResultButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResultButtonMouseClicked
        // TODO add your handling code here:
        panelVisiblity(false, false, false, true);
    }//GEN-LAST:event_viewResultButtonMouseClicked

    private void dropStudentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropStudentButtonMouseClicked
        // TODO add your handling code here:
        panelVisiblity(false, false, true, false);
    }//GEN-LAST:event_dropStudentButtonMouseClicked

    private void mainFromAdmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromAdmitMouseClicked
        // TODO add your handling code here:
        panelVisiblity(true, false, false, false);
    }//GEN-LAST:event_mainFromAdmitMouseClicked

    private void mainFromResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromResultMouseClicked
        // TODO add your handling code here:
        panelVisiblity(true, false, false, false);
    }//GEN-LAST:event_mainFromResultMouseClicked

    private void nameField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameField7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField7MouseClicked

    private void nameField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField7ActionPerformed

    private void idField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idField7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idField7MouseClicked

    private void idField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idField7ActionPerformed

    private void fathersNameField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fathersNameField7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fathersNameField7MouseClicked

    private void fathersNameField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathersNameField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathersNameField7ActionPerformed

    private void femaleCheck7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleCheck7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleCheck7ActionPerformed

    private void maleCheck7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleCheck7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleCheck7ActionPerformed

    private void mothersNameField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mothersNameField7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mothersNameField7MouseClicked

    private void mothersNameField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothersNameField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothersNameField7ActionPerformed

    private void mainFromDropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFromDropMouseClicked
        // TODO add your handling code here:
        panelVisiblity(true, false, false, false);
    }//GEN-LAST:event_mainFromDropMouseClicked

    public void panelVisiblity(boolean welcomePanel, boolean addStudentPanel, boolean dropStudentPanel, boolean viewResultPanel){
        this.welcomePanel.setVisible(welcomePanel);
        this.addStudentPanel.setVisible(addStudentPanel);
        this.dropStudentPanel.setVisible(dropStudentPanel);
        this.viewResultPanel.setVisible(viewResultPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addButtonPanel3;
    private javax.swing.JPanel addButtonPanel4;
    private javax.swing.JPanel addButtonPanel5;
    private javax.swing.JPanel addButtonPanel6;
    private javax.swing.JPanel addButtonPanel7;
    private javax.swing.JPanel addStudentPanel;
    private javax.swing.JPanel admitStudentButton;
    private javax.swing.JPanel createProfileButtonPanel12;
    private javax.swing.JPanel createProfileButtonPanel4;
    private javax.swing.JPanel createProfileButtonPanel6;
    private javax.swing.JPanel dropStudentButton;
    private javax.swing.JPanel dropStudentPanel;
    private javax.swing.JLabel fatherLabel4;
    private javax.swing.JLabel fatherLabel6;
    private javax.swing.JLabel fatherLabel7;
    private javax.swing.JTextField fathersNameField4;
    private javax.swing.JTextField fathersNameField6;
    private javax.swing.JTextField fathersNameField7;
    private javax.swing.JRadioButton femaleCheck4;
    private javax.swing.JRadioButton femaleCheck6;
    private javax.swing.JRadioButton femaleCheck7;
    private javax.swing.JLabel genderLabel4;
    private javax.swing.JLabel genderLabel6;
    private javax.swing.JLabel genderLabel7;
    private javax.swing.JTextField idField4;
    private javax.swing.JTextField idField6;
    private javax.swing.JTextField idField7;
    private javax.swing.JLabel idLabel4;
    private javax.swing.JLabel idLabel6;
    private javax.swing.JLabel idLabel7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JList<String> jList10;
    private javax.swing.JList<String> jList11;
    private javax.swing.JList<String> jList14;
    private javax.swing.JList<String> jList15;
    private javax.swing.JList<String> jList16;
    private javax.swing.JList<String> jList17;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel mainFromAdmit;
    private javax.swing.JPanel mainFromDrop;
    private javax.swing.JPanel mainFromResult;
    private javax.swing.JRadioButton maleCheck4;
    private javax.swing.JRadioButton maleCheck6;
    private javax.swing.JRadioButton maleCheck7;
    private javax.swing.JLabel motherLabel4;
    private javax.swing.JLabel motherLabel6;
    private javax.swing.JLabel motherLabel7;
    private javax.swing.JTextField mothersNameField4;
    private javax.swing.JTextField mothersNameField6;
    private javax.swing.JTextField mothersNameField7;
    private javax.swing.JTextField nameField4;
    private javax.swing.JTextField nameField6;
    private javax.swing.JTextField nameField7;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JLabel nameLabel6;
    private javax.swing.JLabel nameLabel7;
    private javax.swing.JPanel removeButtonPanel6;
    private javax.swing.JPanel removeButtonPanel7;
    private javax.swing.JLabel showSelectedCourses4;
    private javax.swing.JLabel showSelectedCourses6;
    private javax.swing.JLabel showSelectedCourses7;
    private javax.swing.JPanel viewResultButton;
    private javax.swing.JPanel viewResultPanel;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
